name: Build SDL Game

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LibSDL
      run: sudo apt install libsdl1.2-dev libsdl-image1.2-dev
    - name: Build (make) bomber.sdl
      run: make bomber.sdl

